### ISSUE TITLE
Why preprocess the new numerical features obtained from one hot encoding?

### ISSUE THREAD

**Issue by isCopyman** [dholzmueller/pytabkit#4]
![image](https://github.com/user-attachments/assets/4bc02886-fd05-46a8-91a4-7e4dcc080249)
As highlighted in green in the picture, is there any consideration here? I don't quite understand this operation

**Comment by dholzmueller** [comment]
We did this because we got slightly better results with it on the meta-train benchmark (may not be statistically significant) than when not applying it to the one-hot encoded features. It is a bit ugly and I am not fully satisfied with it but after trying a few different options I didn't find a version that matched these results while also being elegant. Also, it is not clear to me what should be the best option. Normalize component-wise? Don't normalize at all? Normalize the whole one-hot vector?

I'm closing the issue but feel free to follow up if you have more questions.
