### ISSUE TITLE
Issue when combining with Pipeline

### ISSUE THREAD

**Issue by lepennec** [dholzmueller/pytabkit#7]
Dear all,

congrats for this great paper (and the implementation). I would like to experiment with RealMLP for classification but I stumble with a strange bug when using them in a Pipeline
```
sklearn.base.is_classifier(Pipeline(steps=[('classifier', RealMLP_TD_Classifier())]))
```
yield `false` while with sklearn predictor
```
sklearn.base.is_classifier(Pipeline(steps=[('classifier', HistGradientBoostingClassifier())]))
```
the answer is `true`. This may be related to the fact that your classes does not derive from `ClassifierMixin` (or `RegressorMixin`).

**Comment by dholzmueller** [comment]
Thank you for pointing this out. This seems to be an issue with scikit-learn 1.6 because we didn't implement the new tags interface yet. I'll try to implement it later, meanwhile you might want to downgrade scikit-learn to 1.5. 

(Our classes derive from `ClassifierMixin` or `RegressorMixin` indirectly through `AlgInterfaceClassifier` and `AlgInterfaceRegressor`.)

**Comment by dholzmueller** [comment]
I fixed the issue by changing the order of double inheritance in `AlgInterfaceClassifier` and `AlgInterfaceRegressor`. Since skorch is currently not supporting scikit-learn 1.6, I added a requirement `<1.6` to the pyproject.toml, but this only concerns FTT, MLP-PLR, MLP and ResNet. The other methods including RealMLP should now be compatible with sklearn 1.6.
